[template]
src = "elasticsearch.yml.tmpl"
dest = "/usr/share/elasticsearch/config/elasticsearch.yml"
prefix = "es"
keys = [
  "/cluster/blocks/read/only",
  "/cluster/info/update/interval",
  "/cluster/name",
  "/cluster/routing/allocation/allow/rebalance",
  "/cluster/routing/allocation/awareness/attributes",
  "/cluster/routing/allocation/awareness/force/zone/values",
  "/cluster/routing/allocation/balance/index",
  "/cluster/routing/allocation/balance/shard",
  "/cluster/routing/allocation/balance/shard",
  "/cluster/routing/allocation/balance/threshold",
  "/cluster/routing/allocation/cluster/concurrent/rebalance",
  "/cluster/routing/allocation/disk/include/relocations",
  "/cluster/routing/allocation/disk/threshold/enabled",
  "/cluster/routing/allocation/disk/watermark/high",
  "/cluster/routing/allocation/disk/watermark/low",
  "/cluster/routing/allocation/enable",
  "/cluster/routing/allocation/exclude/host",
  "/cluster/routing/allocation/exclude/ip",
  "/cluster/routing/allocation/exclude/name",
  "/cluster/routing/allocation/include/host",
  "/cluster/routing/allocation/include/ip",
  "/cluster/routing/allocation/include/name",
  "/cluster/routing/allocation/node/concurrent/recoveries",
  "/cluster/routing/allocation/node/initial/primaries/recoveries",
  "/cluster/routing/allocation/require/host",
  "/cluster/routing/allocation/require/ip",
  "/cluster/routing/allocation/require/name",
  "/cluster/routing/allocation/same/shard/host",
  "/cluster/routing/allocation/total/shards/per/node",
  "/cluster/routing/rebalance/enable",
  "/discovery/zen/minimum/master/nodes",
  "/discovery/zen/ping/unicast/hosts",
  "/gateway/expected/data/nodes",
  "/gateway/expected/master/nodes",
  "/gateway/expected/nodes",
  "/gateway/recover/after/data/nodes",
  "/gateway/recover/after/master/nodes",
  "/gateway/recover/after/nodes",
  "/gateway/recover/after/time",
  "/http/bind/host",
  "/http/compression",
  "/http/compression/level",
  "/http/cors/allow/credentials",
  "/http/cors/allow/headers",
  "/http/cors/allow/methods",
  "/http/cors/allow/origin",
  "/http/cors/enabled",
  "/http/cors/max/age",
  "/http/detailed/errors",
  "/http/enabled",
  "/http/host",
  "/http/max/content/length",
  "/http/max/header/size",
  "/http/max/initial/line/length",
  "/http/pipelining",
  "/http/pipelining/max/events",
  "/http/port",
  "/http/publish/host",
  "/http/publish/port",
  "/index/codec",
  "/index/merge/scheduler/max/thread/count",
  "/index/number/of/shards",
  "/index/similarity/default/type",
  "/index/store/type",
  "/indices/breaker/request/limit",
  "/indices/breaker/total/limit",
  "/indices/breaker/total/overhead",
  "/indices/fielddata/cache/size",
  "/indices/memory/index/buffer/size",
  "/indices/memory/max/index/buffer/size",
  "/indices/memory/max/shard/index/buffer/size",
  "/indices/memory/min/index/buffer/size",
  "/indices/queries/cache/size",
  "/indices/recovery/compress",
  "/indices/recovery/concurrent/small/file/streams",
  "/indices/recovery/concurrent/streams",
  "/indices/recovery/file/chunk/size",
  "/indices/recovery/max/bytes/per/sec",
  "/indices/recovery/translog/ops",
  "/indices/recovery/translog/size",
  "/indices/requests/cache/size",
  "/indices/ttl/bulk/size",
  "/indices/ttl/interval",
  "/logger/indices/recovery",
  "/network/bind/host",
  "/network/host",
  "/network/publish/host",
  "/network/tcp/keep/alive",
  "/network/tcp/no/delay",
  "/network/tcp/receive/buffer/size",
  "/network/tcp/reuse/address",
  "/network/tcp/send/buffer/size",
  "/node/data",
  "/node/master",
  "/node/max/local/storage/nodes",
  "/node/type",
  "/node/type",
  "/node/type",
  "/node/type",
  "/path/data",
  "/transport/bind/host",
  "/transport/host",
  "/transport/ping/schedule",
  "/transport/publish/host",
  "/transport/tcp/compress",
  "/transport/tcp/connect/timeout",
  "/transport/tcp/port",
  "/transport/tcp/port",
]
